name: Revel
favicon: null
layout_spectrum: 0.5477300093043596
typography_spectrum: 0.8564456147141755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9779086874332279
  lightness: 0.5018530476372689
  saturation: 0.510355428326875
  rhythmicContrast: 0.682510006474331
purpose: []
